---
title: "Perceptual Difficulty - Norming for Namability"
#output: rmarkdown::github_document
output:
  html_document: default
  #pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data import, include=FALSE}
library(tidyverse)
theme_set(theme_bw())
source("helpers.R")
library(wesanderson)

#df = read.csv("../data/trials_merged.csv", header = TRUE)
#demo = read.csv("../data/subject_info_merged.csv", header = TRUE)

typ1 = read.csv("../data/typ1-example-trials.csv", header = TRUE)
typ2 = read.csv("../data/typ2-example-trials.csv", header = TRUE)
typ1 = separate(typ1,response,into=c("r_material","r_color"),sep=",")
typ1$r_material <- as.character(gsub("\\[","",typ1$r_material))
typ1$r_color <- as.character(gsub("\\]","",typ1$r_color))
typ2$response <-as.character(gsub("\\[","",typ2$response))
typ2$response <-as.character(gsub("\\]","",typ2$response))

```


```{r function, include=FALSE}
typ1 = typ1 %>%
  filter(str_detect(utterance,"bot_check", negate = TRUE)) %>%
  mutate(r_material = as.numeric(r_material)) %>%
  mutate(r_color = as.numeric(r_color)) %>%
  group_by(object) %>%
  mutate(Mean_material = mean(r_material), Mean_color = mean(r_color))

typ2 = typ2 %>%
  filter(str_detect(utterance,"bot_check", negate = TRUE)) %>%
  mutate(response = as.numeric(response)) %>%
  group_by(object) %>%
  mutate(Mean_overall = mean(response))


typ1_subset  = typ1 %>%
    filter(utterance == "bag")

typ1_subset = separate(typ1_subset,object,into=c("obj","mat","col"),sep="_")



wes = wes_palette("Zissou1"
plot_df_subset = function(object_material_color, utt){
  typ1_subset  = typ1 %>%
    filter(object == object_material_color)
  
  typ2_subset = typ2 %>%
  filter(object == object_material_color)
  
  ggplot(typ1_subset) +
  geom_point(aes(x=workerid, y=r_material), color= wes[1], alpha=.6) +
  geom_point(aes(x=workerid, y=r_color),color=wes[3], alpha=.6) +
  geom_point(data=typ2_subset, aes(x=workerid, y=response), color=wes[5], alpha=.6) +
  geom_point(aes(x=1, y=Mean_material), color=wes[1], size=3) +
  geom_point(aes(x=1, y=Mean_color), color=wes[3], size=3) +
  geom_point(data=typ2_subset, aes(x=1, y=Mean_overall), color=wes[5], size=3) +
  scale_color_manual(name=element_blank(), labels = c("a","b","c","d","e","f"), values = colors) +
  labs(title=utt) +
  ylab("rating") +
  theme(plot.title = element_text(face="bold", hjust = 0.5, size=20), legend.title=element_blank())
}

plot_df_subset("bag_paper_blue","Blue paper bag")
plot_df_subset("bag_plastic_original","Original plastic bag")

```


```{r objects, eval=FALSE, include=FALSE}
plot_df_subset(df_split[["bag"]],"Bag")
plot_df_subset(df_split[["ball"]],"Ball")
plot_df_subset(df_split[["boots"]],"Boots")
plot_df_subset(df_split[["bottle"]],"Bottle")
plot_df_subset(df_split[["bowl"]],"Bowl")
plot_df_subset(df_split[["box"]],"Box")
plot_df_subset(df_split[["chair"]],"Chair")
plot_df_subset(df_split[["cup"]],"Cup")
plot_df_subset(df_split[["door"]],"Door")
plot_df_subset(df_split[["jacket"]],"Jacket")
plot_df_subset(df_split[["pitcher"]],"Pitcher")
plot_df_subset(df_split[["plate"]],"Plate")
plot_df_subset(df_split[["pot"]],"Pot")
plot_df_subset(df_split[["ruler"]],"Ruler")
plot_df_subset(df_split[["spoon"]],"Spoon")
plot_df_subset(df_split[["table"]],"Table")
plot_df_subset(df_split[["vase"]],"Vase")
```







