targets = {
    1 : {'label': 'chair_metal_purple', 'condition': 'high_difficulty', 'color': 'purple', 'material': 'metal', 'item': "chair", 'url': 'chair_metal_purple.png'},
    # 2 :  {'label': 'table_metal_blue', 'condition': 'high_difficulty', 'color': 'blue', 'material': 'metal', 'item': "table", 'url': 'table_metal_blue.png'},
    # 3 : {'label': 'table_metal_green', 'condition': 'high_difficulty', 'color': 'green', 'material': 'metal', 'item': "table", 'url': 'table_metal_green.png'},
	# 4 : {'label': 'table_metal_silver_original', 'condition': 'high_difficulty', 'color': 'silver', 'material': 'metal', 'item': "table", 'url': 'table_metal_silver_original.png'},
	# 5 : {'label': 'boot_leather_green', 'condition': 'high_difficulty', 'color': 'green', 'material': 'leather', 'item': "boot", 'url': 'boot_leather_green.png'},
	# 6 : {'label': 'chair_metal_green', 'condition': 'high_difficulty', 'color': 'green', 'material': 'metal', 'item': "chair", 'url': 'chair_metal_green.png'},
	# 7 : {'label': 'plate_paper_blue', 'condition': 'high_difficulty', 'color': 'blue', 'material': 'paper', 'item': "plate", 'url': 'plate_paper_blue.png'},
	# 8 : {'label': 'spoon_wood_green', 'condition': 'high_difficulty', 'color': 'green', 'material': 'wood', 'item': "spoon", 'url': 'spoon_wood_green.png'},
    # 9 : {'label': 'plate_plastic_blue_original', 'condition': 'low_difficulty', 'color': 'blue', 'material': 'plastic', 'item': 'plate', 'url': 'plate_plastic_blue_original.png'},
    # 10 : {'label': 'cup_plastic_green', 'condition': 'low_difficulty', 'color': 'green', 'material': 'plastic', 'item': 'cup', 'url': 'cup_plastic_green.png'},
    # 11 : {'label': 'jacket_denim_purple', 'condition': 'low_difficulty', 'color': 'purple', 'material': 'denim', 'item': 'jacket', 'url': 'jacket_denim_purple.png'},
    # 12 : {'label': 'pitcher_metal_blue', 'condition': 'low_difficulty', 'color': 'blue', 'material': 'metal', 'item': 'pitcher', 'url': 'pitcher_metal_blue.png'},
    # 13 : {'label': 'table_metal_blue', 'condition': 'low_difficulty', 'color': 'blue', 'material': 'metal', 'item': 'table', 'url': 'table_metal_blue.png'},
	# 14 : {'label': 'bottle_glass_green', 'condition': 'low_difficulty', 'color': 'green', 'material': 'glass', 'item': 'bottle', 'url': 'bottle_glass_green.png'},
	# 15 : {'label': 'bottle_plastic_green',  'condition': 'low_difficulty', 'color': 'green', 'material': 'plastic', 'item': 'bottle', 'url': 'bottle_plastic_green.png'},
	# 16 : {'label': 'plate_paper_blue',  'condition': 'low_difficulty', 'color': 'blue', 'material': 'paper', 'item': 'plate', 'url': 'plate_paper_blue.png'}
}

distractors = {
    1 : {'label': 'bag_paper_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'paper', 'item': 'bag', 'url': 'bag_paper_blue.png'},
    2 : {'label': 'bag_paper_brown_original', 'condition': "difficulty_distractor", 'color': 'brown', 'material': 'paper', 'item': 'bag', 'url': 'bag_paper_brown_original.png'},
    3 : {'label': 'bag_paper_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'paper', 'item': 'bag', 'url': 'bag_paper_green.png'},
    4 : {'label': 'bag_plastic_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'plastic', 'item': 'bag', 'url': 'bag_plastic_blue.png'},
    5 : {'label': 'bag_plastic_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'plastic', 'item': 'bag', 'url': 'bag_plastic_green.png'},
    6 : {'label': 'bag_plastic_white_original', 'condition': "difficulty_distractor", 'color': 'white', 'material': 'plastic', 'item': 'bag', 'url': 'bag_plastic_white_original.png'},
    7 : {'label': 'boot_leather_black_original', 'condition': "difficulty_distractor", 'color': 'black', 'material': 'leather', 'item': 'boot', 'url': 'boot_leather_black_original.png'},
    8 : {'label': 'boot_leather_brown', 'condition': "difficulty_distractor", 'color': 'brown', 'material': 'leather', 'item': 'boot', 'url': 'boot_leather_brown.png'},
    9  : {'label': 'boot_leather_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'leather', 'item': 'boot', 'url': 'boot_leather_green.png'},
    10 : {'label': 'boot_rubber_black_original', 'condition': "difficulty_distractor", 'color': 'black', 'material': 'rubber', 'item': 'boot', 'url': 'boot_rubber_black_original.png'},
    11 : {'label': 'boot_rubber_brown', 'condition': "difficulty_distractor", 'color': 'brown', 'material': 'rubber', 'item': 'boot', 'url': 'boot_rubber_brown.png'},
    12 : {'label': 'boot_rubber_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'rubber', 'item': 'boot', 'url': 'boot_rubber_green.png'},
    13 : {'label': 'bottle_glass_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'glass', 'item': 'bottle', 'url': 'bottle_glass_blue.png'},
    14 : {'label': 'bottle_glass_clear_original', 'condition': "difficulty_distractor", 'color': 'clear', 'material': 'glass', 'item': 'bottle', 'url': 'bottle_glass_clear_original.png'},
    15 : {'label': 'bottle_glass_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'glass', 'item': 'bottle', 'url': 'bottle_glass_green.png'},
    16 : {'label': 'bottle_plastic_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'plastic', 'item': 'bottle', 'url': 'bottle_plastic_blue.png'},
    17 : {'label': 'bottle_plastic_clear_original', 'condition': "difficulty_distractor", 'color': 'clear', 'material': 'plastic', 'item': 'bottle', 'url': 'bottle_plastic_clear_original.png'},
    18 : {'label': 'bottle_plastic_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'plastic', 'item': 'bottle', 'url': 'bottle_plastic_green.png'},
    19 : {'label': 'bowl_glass_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'glass', 'item': 'bowl', 'url': 'bowl_glass_blue.png'},
    20 : {'label': 'bowl_glass_clear_original', 'condition': "difficulty_distractor", 'color': 'clear', 'material': 'glass', 'item': 'bowl', 'url': 'bowl_glass_clear_original.png'},
    21 : {'label': 'bowl_glass_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'glass', 'item': 'bowl', 'url': 'bowl_glass_green.png'},
    22 : {'label': 'bowl_metal_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'metal', 'item': 'bowl', 'url': 'bowl_metal_blue.png'},
    23 : {'label': 'bowl_metal_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'metal', 'item': 'bowl', 'url': 'bowl_metal_green.png'},
    24 : {'label': 'bowl_metal_silver_original', 'condition': "difficulty_distractor", 'color': 'silver', 'material': 'metal', 'item': 'bowl', 'url': 'bowl_metal_silver_original.png'},
    25 : {'label': 'box_cardboard_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'cardboard', 'item': 'box', 'url': 'box_cardboard_blue.png'},
    26 : {'label': 'box_cardboard_brown_original', 'condition': "difficulty_distractor", 'color': 'brown', 'material': 'cardboard', 'item': 'box', 'url': 'box_cardboard_brown_original.png'},
    27 : {'label': 'box_cardboard_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'cardboard', 'item': 'box', 'url': 'box_cardboard_green.png'},
    28 : {'label': 'box_wood_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'wood', 'item': 'box', 'url': 'box_wood_blue.png'},
    29 : {'label': 'box_wood_brown_original', 'condition': "difficulty_distractor", 'color': 'brown', 'material': 'wood', 'item': 'box', 'url': 'box_wood_brown_original.png'},
    30 : {'label': 'box_wood_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'wood', 'item': 'box', 'url': 'box_wood_green.png'},
    31 : {'label': 'chair_metal_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'metal', 'item': 'chair', 'url': 'chair_metal_green.png'},
    32 : {'label': 'chair_metal_purple', 'condition': "difficulty_distractor", 'color': 'purple', 'material': 'metal', 'item': 'chair', 'url': 'chair_metal_purple.png'},
    33 : {'label': 'chair_metal_silver_original', 'condition': "difficulty_distractor", 'color': 'silver', 'material': 'metal', 'item': 'chair', 'url': 'chair_metal_silver_original.png'},
    34 : {'label': 'chair_plastic_blue_original', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'plastic', 'item': 'chair', 'url': 'chair_plastic_blue_original.png'},
    35 : {'label': 'chair_plastic_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'plastic', 'item': 'chair', 'url': 'chair_plastic_green.png'},
    36 : {'label': 'chair_plastic_purple', 'condition': "difficulty_distractor", 'color': 'purple', 'material': 'plastic', 'item': 'chair', 'url': 'chair_plastic_purple.png'},
    37 : {'label': 'chair_wood_brown_original', 'condition': "difficulty_distractor", 'color': 'brown', 'material': 'wood', 'item': 'chair', 'url': 'chair_wood_brown_original.png'},
    38 : {'label': 'chair_wood_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'wood', 'item': 'chair', 'url': 'chair_wood_green.png'},
    39 : {'label': 'chair_wood_purple', 'condition': "difficulty_distractor", 'color': 'purple', 'material': 'wood', 'item': 'chair', 'url': 'chair_wood_purple.png'},
    40 : {'label': 'cup_metal_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'metal', 'item': 'cup', 'url': 'cup_metal_blue.png'},
    41 : {'label': 'cup_metal_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'metal', 'item': 'cup', 'url': 'cup_metal_green.png'},
    42 : {'label': 'cup_metal_silver_original', 'condition': "difficulty_distractor", 'color': 'silver', 'material': 'metal', 'item': 'cup', 'url': 'cup_metal_silver_original.png'},
    43 : {'label': 'cup_plastic_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'plastic', 'item': 'cup', 'url': 'cup_plastic_blue.png'},
    44 : {'label': 'cup_plastic_clear_original', 'condition': "difficulty_distractor", 'color': 'clear', 'material': 'plastic', 'item': 'cup', 'url': 'cup_plastic_clear_original.png'},
    45 : {'label': 'cup_plastic_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'plastic', 'item': 'cup', 'url': 'cup_plastic_green.png'},
    46 : {'label': 'jacket_denim_blue_original', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'denim', 'item': 'jacket', 'url': 'jacket_denim_blue_original.png'},
    47 : {'label': 'jacket_denim_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'denim', 'item': 'jacket', 'url': 'jacket_denim_green.png'},
    48 : {'label': 'jacket_denim_purple', 'condition': "difficulty_distractor", 'color': 'purple', 'material': 'denim', 'item': 'jacket', 'url': 'jacket_denim_purple.png'},
    49 : {'label': 'jacket_leather_black_original', 'condition': "difficulty_distractor", 'color': 'black', 'material': 'leather', 'item': 'jacket', 'url': 'jacket_leather_black_original.png'},
    50 : {'label': 'jacket_leather_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'leather', 'item': 'jacket', 'url': 'jacket_leather_green.png'},
    51 : {'label': 'jacket_leather_purple', 'condition': "difficulty_distractor", 'color': 'purple', 'material': 'leather', 'item': 'jacket', 'url': 'jacket_leather_purple.png'},
    52 : {'label': 'pitcher_glass_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'glass', 'item': 'pitcher', 'url': 'pitcher_glass_blue.png'},
    53 : {'label': 'pitcher_glass_clear_original', 'condition': "difficulty_distractor", 'color': 'clear', 'material': 'glass', 'item': 'pitcher', 'url': 'pitcher_glass_clear_original.png'},
    54 : {'label': 'pitcher_glass_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'glass', 'item': 'pitcher', 'url': 'pitcher_glass_green.png'},
    55 : {'label': 'pitcher_metal_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'metal', 'item': 'pitcher', 'url': 'pitcher_metal_blue.png'},
    56 : {'label': 'pitcher_metal_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'metal', 'item': 'pitcher', 'url': 'pitcher_metal_green.png'},
    57 : {'label': 'pitcher_metal_silver_original', 'condition': "difficulty_distractor", 'color': 'silver', 'material': 'metal', 'item': 'pitcher', 'url': 'pitcher_metal_silver_original.png'},
    58 : {'label': 'pitcher_plastic_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'plastic', 'item': 'pitcher', 'url': 'pitcher_plastic_blue.png'},
    59 : {'label': 'pitcher_plastic_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'plastic', 'item': 'pitcher', 'url': 'pitcher_plastic_green.png'},
    60 : {'label': 'pitcher_plastic_white_original', 'condition': "difficulty_distractor", 'color': 'white', 'material': 'plastic', 'item': 'pitcher', 'url': 'pitcher_plastic_white_original.png'},
    61 : {'label': 'plate_paper_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'paper', 'item': 'plate', 'url': 'plate_paper_blue.png'},
    62 : {'label': 'plate_paper_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'paper', 'item': 'plate', 'url': 'plate_paper_green.png'},
    63 : {'label': 'plate_paper_white_original', 'condition': "difficulty_distractor", 'color': 'white', 'material': 'paper', 'item': 'plate', 'url': 'plate_paper_white_original.png'},
    64 : {'label': 'plate_plastic_blue_original', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'plastic', 'item': 'plate', 'url': 'plate_plastic_blue_original.png'},
    65 : {'label': 'plate_plastic_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'plastic', 'item': 'plate', 'url': 'plate_plastic_green.png'},
    66 : {'label': 'plate_plastic_pink', 'condition': "difficulty_distractor", 'color': 'pink', 'material': 'plastic', 'item': 'plate', 'url': 'plate_plastic_pink.png'},
    67 : {'label': 'spoon_metal_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'metal', 'item': 'spoon', 'url': 'spoon_metal_blue.png'},
    68 : {'label': 'spoon_metal_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'metal', 'item': 'spoon', 'url': 'spoon_metal_green.png'},
    69 : {'label': 'spoon_metal_silver_original', 'condition': "difficulty_distractor", 'color': 'silver', 'material': 'metal', 'item': 'spoon', 'url': 'spoon_metal_silver_original.png'},
    70 : {'label': 'spoon_plastic_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'plastic', 'item': 'spoon', 'url': 'spoon_plastic_blue.png'},
    71 : {'label': 'spoon_plastic_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'plastic', 'item': 'spoon', 'url': 'spoon_plastic_green.png'},
    72 : {'label': 'spoon_plastic_white_original', 'condition': "difficulty_distractor", 'color': 'white', 'material': 'plastic', 'item': 'spoon', 'url': 'spoon_plastic_white_original.png'},
    73 : {'label': 'spoon_wood_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'wood', 'item': 'spoon', 'url': 'spoon_wood_blue.png'},
    74 : {'label': 'spoon_wood_brown_original', 'condition': "difficulty_distractor", 'color': 'brown', 'material': 'wood', 'item': 'spoon', 'url': 'spoon_wood_brown_original.png'},
    75 : {'label': 'spoon_wood_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'wood', 'item': 'spoon', 'url': 'spoon_wood_green.png'},
    76 : {'label': 'table_metal_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'metal', 'item': 'table', 'url': 'table_metal_blue.png'},
    77 : {'label': 'table_metal_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'metal', 'item': 'table', 'url': 'table_metal_green.png'},
    78 : {'label': 'table_metal_silver_original', 'condition': "difficulty_distractor", 'color': 'silver', 'material': 'metal', 'item': 'table', 'url': 'table_metal_silver_original.png'},
    79 : {'label': 'table_wood_blue', 'condition': "difficulty_distractor", 'color': 'blue', 'material': 'wood', 'item': 'table', 'url': 'table_wood_blue.png'},
    80 : {'label': 'table_wood_brown_original', 'condition': "difficulty_distractor", 'color': 'brown', 'material': 'wood', 'item': 'table', 'url': 'table_wood_brown_original.png'},
    81 : {'label': 'table_wood_green', 'condition': "difficulty_distractor", 'color': 'green', 'material': 'wood', 'item': 'table', 'url': 'table_wood_green.png'}
}