---
title: "Perceptual Difficulty - Norming for Typicality"
#output: rmarkdown::github_document
output:
  html_document: default
  #pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data import, include=FALSE}
library(tidyverse)
theme_set(theme_bw())
source("helpers.R")
library(wesanderson)

#df = read.csv("../data/trials_merged.csv", header = TRUE)
#demo = read.csv("../data/subject_info_merged.csv", header = TRUE)

typ1 = read.csv("../data/typ1-example-trials.csv", header = TRUE)
typ2 = read.csv("../data/typ2-example-trials.csv", header = TRUE)

typ1 = separate(typ1,response,into=c("r_material","r_color"),sep=",")
typ1$r_material <- as.character(gsub("\\[","",typ1$r_material))
typ1$r_color <- as.character(gsub("\\]","",typ1$r_color))
typ2$response <-as.character(gsub("\\[","",typ2$response))
typ2$response <-as.character(gsub("\\]","",typ2$response))

```


```{r function, include=FALSE}
typ1 = typ1 %>%
  filter(str_detect(utterance,"bot_check", negate = TRUE)) %>%
  mutate(r_material = as.numeric(r_material)) %>%
  mutate(r_color = as.numeric(r_color)) %>%
  group_by(object) %>%
  mutate(Material_typicality = mean(r_material), Color_typicality = mean(r_color))

typ2 = typ2 %>%
  filter(str_detect(utterance,"bot_check", negate = TRUE)) %>%
  mutate(response = as.numeric(response)) %>%
  group_by(object) %>%
  mutate(Overall_typicality = mean(response))

plot_df_subset = function(obj) {
  
  typ2_subset = typ2 %>%
    filter(utterance == obj) %>%
    distinct(object, .keep_all = TRUE)
  
  typ1_subset  = typ1 %>%
    filter(utterance == obj) %>%
    distinct(object, .keep_all = TRUE) %>%
    mutate(id = object)
  
  df = merge(typ1_subset, typ2_subset, by="object")
  df = separate(df,object,into=c("object","material","color"),sep="_")
  df = df %>% select("id", "object","material","color","Color_typicality", "Material_typicality", "Overall_typicality")
  df_long = gather(df,condition,value,Color_typicality, Material_typicality, Overall_typicality)
  
  ggplot(df_long, aes(x=condition, y=value, color=color, shape=material, group=id)) +
    geom_point() +
    geom_line() +
    geom_text(aes(label=ifelse(condition=="Color_typicality",paste(color,material,object,sep = " "), "")), hjust=1, vjust=-2, size=3) +
    labs(title=obj) +
    xlab("") +
    ylab("rating") +
    scale_color_manual(values=wes_palette("GrandBudapest1"))+
    theme(plot.title = element_text(face="bold", hjust = 0.5, size=20))
}  

```

```{r objects, echo=FALSE}
plot_df_subset("bag")
plot_df_subset("boot")
```

```{r function old, eval=FALSE, include=FALSE}
# wes = wes_palette("Zissou1")
# 
# plot_df_subset = function(object_material_color, utt){
#   typ1_subset  = typ1 %>%
#     filter(object == object_material_color)
#   
#   typ2_subset = typ2 %>%
#   filter(object == object_material_color)
#   
#   ggplot(typ1_subset) +
#     geom_point(aes(x=workerid, y=r_material), color= wes[1], alpha=.6) +
#     geom_point(aes(x=workerid, y=r_color),color=wes[3], alpha=.6) +
#     geom_point(data=typ2_subset, aes(x=workerid, y=response), color=wes[5], alpha=.6) +
#     geom_point(aes(x=1, y=Mean_material), color=wes[1], size=3) +
#     geom_point(aes(x=1, y=Mean_color), color=wes[3], size=3) +
#     geom_point(data=typ2_subset, aes(x=1, y=Mean_overall), color=wes[5], size=3) +
#     scale_color_manual(name=element_blank(), labels = c("a","b","c","d","e","f"), values = colors) +
#     labs(title=utt) +
#     ylab("rating") +
#     theme(plot.title = element_text(face="bold", hjust = 0.5, size=20), legend.title=element_blank())
# }
# 
# plot_df_subset("bag_paper_blue","Blue paper bag")
# plot_df_subset("bag_plastic_original","Original plastic bag")

```








